[project]
name = "christmas-lights-scripts"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "geopy>=2.4.1",
    "boto3>=1.34.0",
    "python-dotenv>=1.2.1",
    "requests>=2.32.5",
]
